import { useEffect, useState } from 'react'
import type { LocalProject } from './LocalProjects'
import { ToolResultCard } from './ToolResultCard'
type Configuration = { revision:number; preset:string; previewEnabled:boolean; mysqlEnabled:boolean; previewMinutes:number }
export function ProjectRuntimeEditor({project,onChanged}:{project:LocalProject;onChanged:()=>Promise<void>}){
  const [open,setOpen]=useState(false),[config,setConfig]=useState<Configuration>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [checks,setChecks]=useState<Record<string,unknown>[]>([])
  const [images,setImages]=useState<Record<string,unknown>[]>([])
  useEffect(()=>{if(open)void fetch('/api/local-runtime-environment').then(r=>r.json()).then(r=>setImages(r.images??[])).catch(e=>setError(String(e)))},[open])
  useEffect(()=>{if(!open)return;let disposed=false;void Promise.all([fetch(`/api/local-projects/${project.id}/runtime`).then(r=>r.json()),fetch(`/api/local-projects/${project.id}/mysql-verifications`).then(r=>r.json())]).then(([c,list])=>{if(!disposed){setConfig(c);setChecks(list)}}).catch(e=>setError(String(e)));return()=>{disposed=true}},[open,project.id,project.revision])
  async function save(){if(!config)return;setBusy(true);setError('');try{const r=await fetch(`/api/local-projects/${project.id}/runtime`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...config,expectedProjectRevision:project.revision,expectedRuntimeRevision:config.revision,isolationConfirmed:confirmed})});const data=await r.json();if(!r.ok)throw new Error(data.message??'保存失败');setConfig(data);setConfirmed(false);await onChanged()}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function cleanup(id:string){if(!window.confirm('仅回收这次 MySQL 验证的本机隔离资源？验证记录保留，不操作任何生产备份。'))return;setBusy(true);try{const r=await fetch(`/api/local-projects/${project.id}/mysql-verifications/${id}/cleanup`,{method:'POST'});if(!r.ok)throw new Error('回收未确认，请检查运行记录');setChecks(await fetch(`/api/local-projects/${project.id}/mysql-verifications`).then(r=>r.json()))}catch(e){setError(String(e))}finally{setBusy(false)}}
  return <details className="project-runtime" onToggle={e=>setOpen(e.currentTarget.open)}><summary>预览与测试设置</summary>{config&&<div className="project-runtime-content"><p className="hint">当前预设：时光序 Spring Boot。预览用 H2 合成数据；MySQL 验证用专用临时数据库，内部网络仅连接测试与数据库。其他技术栈需另行适配。</p><div className="runtime-fields"><label className="project-checkbox"><input type="checkbox" checked={config.previewEnabled} onChange={e=>setConfig({...config,previewEnabled:e.target.checked})}/>允许隔离预览</label><label className="project-checkbox"><input type="checkbox" checked={config.mysqlEnabled} onChange={e=>setConfig({...config,mysqlEnabled:e.target.checked})}/>允许 MySQL 集成验证</label><label>预览时限（分钟）<input type="number" min={5} max={30} value={config.previewMinutes} onChange={e=>setConfig({...config,previewMinutes:Number(e.target.value)})}/></label></div><p className="hint">容器限制 CPU、内存和进程数；MySQL 验证使用有容量上限的临时空间。固定镜像由本机管理者维护，这里不接受命令、数据库地址或密码。</p><label className="project-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已确认合成数据与隔离范围；保存后需新建编码会话，旧发布任务不能继续操作。</label><button className="secondary" disabled={busy||!confirmed||project.archived} onClick={()=>void save()}>保存运行设置</button></div>}<details><summary>固定镜像与缓存</summary>{images.map(r=><p key={String(r.type)}>{String(r.type)}：{r.available===true?`${(Number(r.bytes)/1024/1024).toFixed(0)} MiB，摘要 ${String(r.configuredId).slice(0,19)}…`:'尚未确认'}<small className="hint"> · {String(r.retention)}</small></p>)}<p className="hint">源码快照上限 128 MiB，单文件 8 MiB；MySQL 数据临时空间 512 MiB，测试工作空间 1536 MiB。预览工作卷没有磁盘配额，不将其显示为受限容量。</p></details><details><summary>MySQL 验证记录 · {checks.length}</summary>{checks.length===0?<p>尚未运行，不代表集成测试通过。</p>:checks.map(r=><article key={String(r.verificationId)}><ToolResultCard receipt={r} createdAt={typeof r.createdAt === "string" ? r.createdAt : undefined}/>{r.state==='CLEANUP_REQUIRED'&&<button className="secondary" disabled={busy} onClick={()=>void cleanup(String(r.verificationId))}>回收本次隔离资源</button>}</article>)}</details>{error&&<p role="alert" className="error-text">{error}</p>}</details>
}
